from selenium.webdriver.common.by import By


class BaseLocators:
    LOGIN_PAGE = (By.CLASS_NAME, 'login-title')
    LOGIN_USERNAME = (By.ID, 'LoginUsername')
    LOGIN_PASSWORD = (By.ID, 'LoginPassword')
    SIGN_BUTTON = (By.ID, 'loginBtn')
    SERVICE_MANAGER_WINDOW = (By.ID, 'cwc_header')

    BODY = (By.TAG_NAME, "body")
    PRELOADER = (By.XPATH, "//div[text()='Загрузка...']")
    MESSAGE = (By.CSS_SELECTOR, 'div[class="messageTrayElement infoMsg"]')

    CHANGE_MANAGEMENT_BUTTON = (By.XPATH, "(//span[text()='Управление изменениями'])[2]")
    CREATE_NEW_CHANGE_BUTTON = (By.XPATH, "//span[text()='Создание нового изменения']")
    CHANGE_MODEL_TITTLE = (By.XPATH, "//span[text()='Выбор модели изменения']")
    SEARCH_FIELD = (By.ID, "X2")
    FIND_BUTTON = (By.ID, "X2FindButton")
    FOUND_MODEL = (By.XPATH, "//a[text()='Normal Significant RFC']")
    CREATE_ZNI_FORM = (By.ID, "X4Readonly")

    INITIATOR_FIELD = (By.ID, "X17")
    INITIATOR_SELECT = (By.XPATH, "//b[text()='AutoTest']")
    SERVICE_FIELD = (By.XPATH, "(//input[@id='X69'])[1]")
    SERVICE_SELECT = (By.XPATH, "//div[@title='CI9954462']")
    WORKING_GROUP = (By.ID, "X71")
    KE_FIELD = (By.ID, "X79_1")
    KE_SELECT = (By.XPATH, "//b[text()='Тестовая КЕ ЕМИАС']")
    DATE_INPUT = (By.ID, 'X44')
    SHORT_DESCRIPTION_FIELD = (By.ID, "X22")
    DESCRIPTION_FIELD = (By.ID, 'X24View')
    DESCRIPTION_INPUT_FIELD = (By.ID, 'X24')
    SAVE_BUTTON = (By.XPATH, "//button[text()='Сохранить']")

    TASKS_BUTTON = (By.LINK_TEXT, "Задачи")
    CREATE_TASK_BUTTON = (By.ID, "X94Btn")
    REG_TASK_TITTLE = (By.XPATH, "//h2[text()='Задача изменения — ']")
    SAVE_AND_EXIT_BUTTON = (By.XPATH, "//button[text()='Сохранить и выйти']")
    CREATED_TASK = (By.ID, "dtlr_X102_1")
    CREATED_TASK_PHASE = (By.ID, "X106_1")
    CREATED_TASK_STATUS = (By.ID, "X108_1")

    FOR_PLANNING_BUTTON = (By.XPATH, "//button[text()='На планирование']")
    REFRESH_BUTTON = (By.XPATH, "(//button[text()='Обновить'])[3]")
    YES_BUTTON = (By.ID, "y")
    OK_BUTTON = (By.ID, "o")
    ON_APPROVAL_BUTTON = (By.XPATH, "//button[text()='На согласование']")
    APPROVAL_BUTTON = (By.XPATH, "//a[text()='Согласование ']")
    RIGHT_BUTTON = (By.CSS_SELECTOR, 'a[class="notebookRightButton"]')
    APPROVAL_TAB = (By.XPATH, "//label[text()='Код записи согласования:']")
    COORDINATION_TYPE_BUTTON = (By.ID, "X560Button")
    COORDINATION_TYPE_SELECT = (By.ID, "X560Popup_2")
    COORDINATION_LIST = (By.ID, "X566_1Button")
    COORDINATION_LIST_SELECT = (By.XPATH, "//div[text()='АРИСТОВ АРТУР (ARISTOV.AV)']")
    START_AGREEMENT = (By.XPATH, "//button[text()='Запустить согласование']")
    APPROVE_BUTTON = (By.XPATH, "//button[text()='Согласовать']")

    TASKS_NUMBER = (By.ID, "X108_1")
    ACTIVATE_BUTTON = (By.XPATH, "//button[text()='Активировать']")
    ZNI_PHASE = (By.ID, "X8")

    COMMENT_CLOSE_CLICK = (By.ID, "X41Edit")
    COMMENT_CLOSE_FIELD = (By.ID, "X41")
    CODE_CLOSE_FIELD = (By.ID, "X44")

    TO_WORK_BUTTON = (By.XPATH, "//button[text()='В работу']")
    ZNI_STATUS = (By.ID, "X12")
    ZNI_NEW_STATUS = (By.ID, "X14")

    LAUNCHING_TASKS_BUTTON = (By.XPATH, "//button[text()='Запустить задачи']")
    NUMBER_TASK_BUTTON = (By.ID, "X108_1")
    RESPONSIBLE_FIELD = (By.ID, "X38")
    RESPONSIBLE_SELECT = (By.XPATH, "//div[@value='АРИСТОВ АРТУР (ARISTOV.AV)']")

    EXECUTE_BUTTON = (By.XPATH, "//button[text()='Выполнить']")
    CLOSE_BUTTON = (By.XPATH, "//button[text()='Закрыть']")
    NUMBER_ZNI = (By.ID, "X8")
    SEARCH_ZNI_BUTTON = (By.XPATH, "//span[text()='Поиск изменений']")
    SEARCH_ZNI_FIELD = (By.ID, "X12")
    SEARCH_BUTTON = (By.XPATH, "//button[text()='Поиск']")

    CREATED_TASK_PHASE_SECOND = (By.ID, "X110_1")
    CREATED_TASK_STATUS_SECOND = (By.ID, "X112_1")
    CODE_CLOSE_LIST = (By.ID, "X91Button")
    CODE_CLOSE_LIST_SELECT = (By.XPATH, "//div[@value='Выполнено успешно']")
